### ISSUE TITLE
[Subtask] Too many jobs for Backend Integration Test CI

### ISSUE THREAD

**Issue by mchades** [apache/gravitino#4583]
### Describe the subtask

there are 12 jobs in Backend Integration Test workflow:
```yaml
strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 8, 11, 17 ]
        test-mode: [ embedded, deploy ]
        backend: [ mysql, h2]
```

I think the h2 backend only needs to be tested in embedded test mode; the mysql backend only needs to be tested in deployed test mode

### Parent issue

#3834
