### ISSUE TITLE
[Improvement] Support passing catalog information by warehouse query param in IRC

### ISSUE THREAD

**Issue by FANNG1** [apache/gravitino#7442]
### What would you like to be improved?

According to the Iceberg REST spec, all clients should the config interface to get catalog configuration, we could use `warehouse` as the catalog identifier to get catalog configuration , then the user doesn't need to specify the catalog configuration in client side.
```
paths:
  /v1/config:

    get:
      tags:
        - Configuration API
      summary: List all catalog configuration settings
      operationId: getConfig
      parameters:
        - name: warehouse
          in: query
          required: false
          schema:
            type: string
          description: Warehouse location or identifier to request from the service
      description:
        "
        All REST clients should first call this route to get catalog configuration
        properties from the server to configure the catalog and its HTTP client.
```
